### ISSUE TITLE
Stripe API version (2017-08-15) does not accept a WebHook URL: «You passed an empty string for 'expand'»

### ISSUE THREAD

**Issue by Aresinho** [mage2pro/stripe#49]
When trying to add the webhook url as specified in https://mage2.pro/t/topic/977 it doest not work. 

Stripe Displays the Following Information:

> You passed an empty string for 'expand'. We assume empty values are an attempt to unset a parameter; however 'expand' cannot be unset. You should remove 'expand' from your request or supply a non-empty value.

**Comment by dmitry-fedyuk** [comment]
Which website have you bought the extension's license for?

**Comment by Aresinho** [comment]
Haven't bought it yet. We are testing it first to make sure it works before buying it. We are following your policy as specified here:

https://mage2.pro/t/topic/2590

**Comment by dmitry-fedyuk** [comment]
I support only the paying customers.

**Comment by Aresinho** [comment]
Whats the point of testing the extension if we cannot get it to work? Can you guarantee that if we buy the extension this will be solved?

If not I guess we will be buying another extension.

Thanks

**Comment by dmitry-fedyuk** [comment]
Yes, all your issues will be solved after the purchase.

**Comment by Aresinho** [comment]
We've bought the extension. Domain: shopcasita.com. 

So, what's next?

**Comment by dmitry-fedyuk** [comment]
Thanks for the purchase, I will check the issue today.

**Comment by dmitry-fedyuk** [comment]
I am unable to reproduce your issue.
Please provide a screenshot with the error message.

![01](https://user-images.githubusercontent.com/83204/32990309-5fd409ce-cd38-11e7-92e5-7d39d1431486.png)

![02](https://user-images.githubusercontent.com/83204/32990291-0b460844-cd38-11e7-9ee3-58fd38b95b9d.png)

**Comment by Aresinho** [comment]
I was able to add the endpoint. However, we received an email with the following info:

> Hi there,
> 
> We’re contacting you because we’ve had some trouble delivering data to a webhook endpoint associated with your Shopcasita account in live mode. Webhooks are used to notify your server about events that happen in your Stripe account, such as a payout completing or an invoice being created. The failing webhook endpoint is https://shopcasita.com/index.php/dfe-stripe.
> 
> You or someone on your team has added that endpoint in your Stripe webhook settings, which you can view and edit here: https://dashboard.stripe.com/account/webhooks.
> 
> Please note that in most cases a failing webhook does not impact your charges or payouts. However, if you use subscriptions we rely on your webhook endpoint to notify you of new invoices. These invoices may be delayed for up to three days if your webhook is unable to successfully receive them.
> 
> We’ve attempted to notify the endpoint 212 times since November 14 at 06:14PM. If this endpoint is important to your application, please try and fix the issue. If you do not need the webhook endpoint you can delete it from your Stripe webhook settings. We will stop sending notifications to your webhook by November 23.
> 
> One recent call to your endpoint failed because of a problem with your host's TLS configuration. For a detailed analysis, click here: https://ssllabs.com/ssltest/analyze.html?d=shopcasita.com:443 You can view the event for this failed notification here: https://dashboard.stripe.com/events/evt_1BO8vIEDt3zGou6dGPwSECdz. To acknowledge receipt of a webhook, your endpoint should return a 2xx HTTP status code.
> 
> For more in depth information about how to use webhooks, we recommend taking a look at our documentation: https://stripe.com/docs/webhooks.
> 
> Yours,
> 
> The Stripe Team

**Comment by dmitry-fedyuk** [comment]
1. It is a different issue, so please create a dedicated issue-topic for it here on GitHub.
2. How have you solved your original "**You passed an empty string for 'expand'**" issue exactly?

**Comment by dmitry-fedyuk** [comment]
No response => closed.
