### ISSUE TITLE
Should I duplicate my post in multiple places?

### ISSUE THREAD

**Issue by terrybakshi** [mage2pro/stripe#5]
Hi after an update to 2.1.6 the checkout page is going in loop i means it keep loading and nothing is happening, upon checking in inspect elements its showing files from the stripe extension are not loading and getting 404 error Can you please fix this issue for me asap. please let me know if you require login details,

Thanks

**Comment by dmitry-fedyuk** [comment]
What is the purpose to duplicate your post in multiple places? https://mage2.pro/t/3702

**Comment by terrybakshi** [comment]
Sorry for the trouble as i was unaware of this support section. So far i have disable the DF_checkout and now the checkout page is visible and but when i go to test stripe mode and add any card to test the payments i am getting error Request does not match any route.

Thanks

**Comment by dmitry-fedyuk** [comment]
Have you implemented all the steps on the [upgrading instruction](https://mage2.pro/t/2233) exactly?

**Comment by terrybakshi** [comment]
yes i did that already

**Comment by dmitry-fedyuk** [comment]
What is "DF_checkout" that you have "disabled", and what the "disable" action mean?

**Comment by terrybakshi** [comment]
ok i am not sure what df checkout is i thought its related to your extension but this is what i did [](http://prnt.sc/ewcshs) to diable the df checkout once i disable it the checkout page is working but after i go to make test payment i get this error (Request does not match any route).

**Comment by dmitry-fedyuk** [comment]
You should now revert all your actions which are not mentioned in the official upgrading instruction, and then accurately imolement the official upgrading instruction step-by-step, checking each step output in console.

**Comment by terrybakshi** [comment]
which methods are you talking about updating magento

**Comment by dmitry-fedyuk** [comment]
I am talking about **my official upgrading instruction**.

**Comment by terrybakshi** [comment]
yes we did follow the official upgrade instructions is there anything else you find in it.

**Comment by dmitry-fedyuk** [comment]
Which locale have you specified on the Step 3 of my official upgrading instruction?

**Comment by terrybakshi** [comment]
en_AU

**Comment by dmitry-fedyuk** [comment]
I have checked your site.
You had the error «**element.prop is not a function**»:
![04](https://cloud.githubusercontent.com/assets/83204/25042754/12add86c-2123-11e7-9e0e-c3d9e0bcc890.png)

**It is an error message and its screenshot.**
It was **YOUR RESPONSIBILITY** to publish the error message and its screenshot.
The **[reporting rules](https://mage2.pro/t/topic/2034)** say:
```
Reporting rules
1. A report should always contain a screenshot.
2. If your screenshot contains a diagnostic message or another meaningful text, then always duplicate it in the textual form.
3. Place an exact diagnostic message to an issue's title. Do not use generic titles.
4. Use separate topics for separate issues. Do not post multiple issues in a single topic.
```
Is it a rocket science for your to read 4 rules and follow them?

The error is a **Magento 2 core bug**, and I have described it **13 months ago**, and have published a fix for it here: https://mage2.pro/t/999
 
I have upgraded your site myself now, but it is the last time I did it for free.

**Comment by terrybakshi** [comment]
Thanks but why on test card i am still getting this error (Request does not match any route).
