### ISSUE TITLE
«Request does not match any route»

### ISSUE THREAD

**Issue by terrybakshi** [mage2pro/stripe#6]
i am still getting this error (Request does not match any route) when trying to pay through stripe test mode. 
![screenshot_11](https://cloud.githubusercontent.com/assets/13229022/25044044/9b8d2b30-2167-11e7-8b0f-b598e512041a.png)

**Comment by dmitry-fedyuk** [comment]
Learn how to clear cache in your browser.
I do not see any problems and successfully placed  and paid an order now:

![01](https://cloud.githubusercontent.com/assets/83204/25057656/6956e2f6-217a-11e7-8736-4437fef21ecc.png)
