### ISSUE TITLE
Can I can a technical support without paying for the extension?

### ISSUE THREAD

**Issue by vishveskrish** [mage2pro/stripe#60]
Hello Team,

We are facing below issue on our store.

1 exception(s):
Exception #0 (Stripe\Error\Api): Invalid response body from API: 400 Bad Request: invalid header value (HTTP response code was 400, json_last_error() was 4)

Exception #0 (Stripe\Error\Api): Invalid response body from API: 400 Bad Request: invalid header value (HTTP response code was 400, json_last_error() was 4)
#0 /mnt/projects/myproject/html/vendor/stripe/stripe-php/lib/ApiRequestor.php(65): Stripe\ApiRequestor->_interpretResponse('400 Bad Request...', 400, Array)
#1 /mnt/projects/myproject/html/vendor/stripe/stripe-php/lib/ApiResource.php(31): Stripe\ApiRequestor->request('get', '/v1/account', Array, Array)
#2 /mnt/projects/myproject/html/vendor/stripe/stripe-php/lib/ApiResource.php(132): Stripe\ApiResource->refresh()
#3 /mnt/projects/myproject/html/vendor/stripe/stripe-php/lib/Account.php(65): Stripe\ApiResource::_retrieve(NULL, NULL)
#4 /mnt/projects/myproject/html/vendor/mage2pro/stripe/Settings.php(48): Stripe\Account::retrieve()
#5 /mnt/projects/myproject/html/vendor/mage2pro/core/Core/lib/cache.php(207): Dfe\Stripe\Settings->Dfe\Stripe\{closure}()
#6 /mnt/projects/myproject/html/vendor/mage2pro/stripe/Settings.php(49): dfc(Object(Dfe\Stripe\Settings), Object(Closure))
#7 /mnt/projects/myproject/html/vendor/mage2pro/stripe/Settings.php(40): Dfe\Stripe\Settings->account()
#8 /mnt/projects/myproject/html/vendor/mage2pro/stripe/FE/Currency.php(65): Dfe\Stripe\Settings->merchantCountry()
#9 /mnt/projects/myproject/html/vendor/mage2pro/core/Core/lib/cache.php(207): Dfe\Stripe\FE\Currency->Dfe\Stripe\FE\{closure}()
#10 /mnt/projects/myproject/html/vendor/mage2pro/stripe/FE/Currency.php(66): dfc(Object(Dfe\Stripe\FE\Currency\Interceptor), Object(Closure))
#11 /mnt/projects/myproject/html/vendor/mage2pro/stripe/FE/Currency.php(55): Dfe\Stripe\FE\Currency->country()
#12 /mnt/projects/myproject/html/vendor/mage2pro/core/Framework/Form/Element/Select2.php(68): Dfe\Stripe\FE\Currency->disabled()
#13 /mnt/projects/myproject/html/vendor/magento/framework/Data/Form/Element/Fieldset.php(213): Df\Framework\Form\Element\Select2->setRenderer(Object(Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element\Interceptor))
#14 /mnt/projects/myproject/html/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\Data\Form\Element\Fieldset->addField('df_payment_stri...', 'Dfe\\Stripe\\FE\\C...', Array, false, false).

Could you please guide us to resolve this issue. 

Quick help always Appreciated!

Thanks,
Vishves Shah

**Comment by dmitry-fedyuk** [comment]
I support the paying customers only.
