### ISSUE TITLE
The extension is not shown in the frontend when using Firecheckout onepage extension

### ISSUE THREAD

**Issue by stifboy** [mage2pro/stripe#64]
The extension is not shown in the front end when using Firecheckout one page extension

https://swissuplabs.com/magento-extensions/one-step-checkout-extension-for-magento-2.html

**Comment by stifboy** [comment]
I am setting up a new store. This is the url http://sociopewin.com

**Comment by dmitry-fedyuk** [comment]
You should buy the license first: https://mage2.pro/t/980
Then I will solve your problem.
