### ISSUE TITLE
TypeError: Cannot read property 'isEnabled' of undefined

### ISSUE THREAD

**Issue by textarea** [mage2pro/stripe#73]
Hello,
first install in my Magento 2.2.6 but after order submit get this js error TypeError: 
TypeError: Cannot read property 'isEnabled' of undefined
    at placeOrder.js:54
    at UiClass.placeOrderInternal (mixin.js:422)
    at UiClass.<anonymous> (main.js:183)
    at proxy (jquery.js:529)
    at main.js:366

**Comment by dmitry-fedyuk** [comment]
Please provide yout website's URL.

**Comment by textarea** [comment]
Sent a private message with credentials.
Thanks

**Comment by dmitry-fedyuk** [comment]
You need to but the module's license first: [https://mage2.pro/t/980](https://mage2.pro/t/topic/980)

**Comment by textarea** [comment]
I'm evaluating your module, I found a bug and I will not buy a license if I cannot test if the module is working right.
Thank you.
