### ISSUE TITLE
Create a licence file

### ISSUE THREAD

**Issue by ArnoVDC** [mage2pro/stripe#74]
You should create a licence file (not the test licence page) in your repository. This way people who don't read the readme.md will know and you have a solid case for issue's like this one: [https://mage2.pro/t/topic/5764](https://mage2.pro/t/topic/5764)

**Comment by dmitry-fedyuk** [comment]
It is not your responsibility to tell me what I should to do, therefore just fuck off.

**Comment by ArnoVDC** [comment]
Just trying to help bro.

**Comment by dmitry-fedyuk** [comment]
Banned too. Next unpaid teacher?
