### ISSUE TITLE
It is not your responsibility to tell me what I should to do, therefore just fuck off.

### ISSUE THREAD

**Issue by jonasGossiaux** [mage2pro/stripe#75]
_Originally posted by @dmitry-fedyuk in https://github.com/mage2pro/stripe/issues/74#issuecomment-445841480_.

This is not appropriate behavior for a vendor of Magento modules or a creator of Open source modules.  You should be considerate of issues that are posted to your repositories and if you don't agree with them you should voice your opinion in a considerate way.

**Comment by dmitry-fedyuk** [comment]
Banned.
