### ISSUE TITLE
Test card 3063 ( 3DSecure required ) error ?

### ISSUE THREAD

**Issue by grazianodimaio** [mage2pro/stripe#78]
Hello,

i'm testing the extension on my site.

I'm using the 4000000000003063 test card for 3d secure on authorize mode, but the site leads me to the success page.

I suppose i should be redirected to another page, or something but i arrive on the success page.

What can i do ?

**Comment by dmitry-fedyuk** [comment]
What is your website's URL?

**Comment by grazianodimaio** [comment]
Hello dmitry,

the url is https://multicashdev.therope.co, it's a development site, and something could not work properly.

thanks

graziano

**Comment by dmitry-fedyuk** [comment]
I support only paid customers.
