### ISSUE TITLE
«bin/magento module:enable --all»: «The file "/composer.json" doesn't exist»

### ISSUE THREAD

**Issue by kkrieger85** [mage2pro/stripe#8]
After installation with composer following error occurs:

```
php bin/magento module:enable --all
                                             
  [Magento\Framework\Exception\FileSystemException]  
  The file "/composer.json" doesn't exist            
                                               
```

**Comment by kkrieger85** [comment]
Magento 2.1.7
PHP 7.0.13

**Comment by dmitry-fedyuk** [comment]
Which website you have bought the license for?

**Comment by kkrieger85** [comment]
no licence, I just wanted to give your module a try.

by now I will not use it in my projects

**Comment by dmitry-fedyuk** [comment]
The triers are on self-service.

**Comment by davidverholen** [comment]
same bug here.

But since I also just tried, I assume you rather have a broken module instead of just listening to 'triers'?

**Comment by dmitry-fedyuk** [comment]
It is a Magento 2 core bug:
[Magento 2 bug: `bin/magento module:enable` fails with the «The file "/composer.json" doesn't exist» message when a Composer package contains multiple Magento modules](https://mage2.pro/t/topic/4219)
I have added a workaround to the **[2.9.9](https://github.com/mage2pro/core/releases/tag/2.9.9)** version of the [mage2pro/core](https://github.com/mage2pro/core) package.  
To fix the issue just [upgrade your extensions](https://mage2.pro/t/topic/2233).
