### ISSUE TITLE
Disable load of Stripe JS on homepage (or while not in checkout)

### ISSUE THREAD

**Issue by zephir1** [mage2pro/stripe#81]
Hi!

In order to optimize the load of the homepage it would be great to remove the https://js.stripe.com/v3/ script that adds an <iframe>

I found out it is being loaded in multishipping.js and tried removing it via cms_index_index.xml but I cannot succeed.

```
        <remove src="Dfe_Stripe::multishipping.js"/>
        <remove src="https://js.stripe.com/v3/"/>
```

How can I achieve this? I believe it would be great to change it by default.

Thanks!

**Comment by dmitry-fedyuk** [comment]
What is your website's URL?

**Comment by zephir1** [comment]
Hi @dmitry-fedyuk 

It is https://bourguignonfloristas.es (I am using Magento 2.2.8 with latest stripe version).

**Comment by dmitry-fedyuk** [comment]
Nobody bought [the module's license](https://mage2.pro/t/980) for this domain.

**Comment by zephir1** [comment]
Hi dmitry,

I'll talk with the store owners in order to get the license. Didn't know it was necessary, as our Stripe partner gave us the composer command directly.

Thanks for your help, I'll get in touch with you in order to fix the issue!
