### ISSUE TITLE
Failed to order - Error 502 Bad Gateway

### ISSUE THREAD

**Issue by graham-haworth** [mage2pro/stripe#83]
Hi there
We have encountered some issues over the weekend with our production site.
Getting a Error 502 Bad Gateway which appears to be coming from cloudflare / freegeoip.app 
Anyone else experiencing issues ?
Is this a hard dependency for your module ?
![image](https://user-images.githubusercontent.com/14865093/61190337-bde77280-a6ee-11e9-8431-dc58175c759b.png)
Kind regards Graham

**Comment by dmitry-fedyuk** [comment]
Provide your website's URL.

**Comment by graham-haworth** [comment]
Give and grow.co.nz<http://grow.co.nz>

Sent from my iPhone

On 15 Jul 2019, at 16:52, Dmitry Fedyuk <notifications@github.com<mailto:notifications@github.com>> wrote:


Provide your website's URL.

**Comment by graham-haworth** [comment]
Sorry without the spaces.
giveandgrow.co.nz<http://giveandgrow.co.nz>
Cheers, Graham

Sent from my iPhone

On 15 Jul 2019, at 17:06, Graham Haworth <graham.haworth@hotmail.com<mailto:graham.haworth@hotmail.com>> wrote:

Give and grow.co.nz<http://grow.co.nz>

Sent from my iPhone

On 15 Jul 2019, at 16:52, Dmitry Fedyuk <notifications@github.com<mailto:notifications@github.com>> wrote:


Provide your website's URL.

**Comment by dmitry-fedyuk** [comment]
Update the [mage2pro/core](https://github.com/mage2pro/core) package to the latest version.
