### ISSUE TITLE
Stripe Webhooks have not yet been configured - Please refer to the documentation for instructions on how to set up your Stripe account.

### ISSUE THREAD

**Issue by elfeffe** [mage2pro/stripe#85]
I have that message always on top of my Magento admin.
But my webhooks are configured and I don't see any error at Stripe Dashboard.
is this a bug or am I missing something?

**Comment by dmitry-fedyuk** [comment]
You can pay for my consultation here: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)
